name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Test with Maven
        run: mvn clean install

      - name: Update Changelog
        run: |
          latestTag=$(git describe --tags $(git rev-list --tags --max-count=1))
          git log ${latestTag}..HEAD --pretty=format:"- %s" > CHANGELOG.md

      - name: Commit and Push Changelog
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update Changelog for release ${{ github.ref }}"
          git push origin HEAD:${{ github.ref }}
