name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }} 

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Test with Maven
        run: mvn clean install

      - name: Create Release on GitHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tag=$(echo "${{ github.ref }}" | sed -n 's|^refs/tags/||p')
          echo "Creating release $tag..."
          gh release create "$tag" ./target/* --notes "Release notes for $tag"
