name: Debug Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug GitHub Token Permissions
      run: echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

    - name: List Files
      run: ls -R

    - name: Create Release on GitHub
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        tag=$(echo "${{ github.ref }}" | sed -n 's|^refs/tags/||p')
        git checkout "${{ github.sha }}"
        echo "Creating release $tag..."
        gh release create $tag ./ -t "Release $tag"
